---
title: "Cleaning fish catch data for fisheries goal estimation"
author: "Marina Espinasse"
date: "`r Sys.Date()`"
output:
  html_document:
    css: '~/github/nor-prep/prep/templates/style.css'
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/nor-prep/prep/templates/norway_banner.html'
  pdf_document:
    toc: true

---

```{r include=FALSE}
library(readxl)
library(readr)
library(dplyr)
library(stringr)
library(kableExtra)
```

# Loading fish landings data (1994 - 2017) for  in Northern Norway 
```{r}
#/Volumes/ftp.imr.no/Fishery/DeliveryDataFiskDir/Fisk0017.csv
temp_catch17 <- read.csv("/Volumes/ftp.imr.no/Fishery/DeliveryDataFiskDir/Fisk0017.csv", sep = ";")
temp_catch99 <- read.csv("/Volumes/ftp.imr.no/Fishery/DeliveryDataFiskDir/Fisk9499.csv", sep = ";")
names<-read.csv("/Volumes/ftp.imr.no/Fishery/DeliveryDataFiskDir/Fiskid.csv", sep = ";")#fish species names in English and Norwegian
komlist<-read.csv("/Volumes/ftp.imr.no/Administrative/komlist.csv", sep = ";")#list of municipalities names and codes
```

# Cleaning and formatting fish landings data: cheking species names
```{r, results="hide"}
temp_catch17 <-select(temp_catch17, -c("Artskode","Fangstaar")) %>% rename("Lengdegr"= "Lengdegr.l.l.")
temp_catch99 <-select(temp_catch99, -Artskode) %>% rename("Lengdegr"= "Lengdegr.l.l.")#remove species code, which is different between 1990s and 2000s
temp_catch<-bind_rows(temp_catch99, temp_catch17)
colnames(temp_catch) <- c("Year", "Month", "Municip_number", "Municip_name","Species",
                          "Coast_ocean", "Region", "Fleet_length", "Catch_weight", "Payed_NOK")
#several norwegian names were used for the same species, let's check all variations
fishnames<-unique(temp_catch$Species)
str_view(fishnames, regex("torsk", ignore_case = TRUE))#Annen Torsk, Nordostarktisk torsk, Torsk, Torsk (oppdrett), Polartorsk
str_view(fishnames, regex("hyse", ignore_case = TRUE))#Hyse, Nordostarktisk hyse , Annen hyse
str_view(fishnames, regex("lodde", ignore_case = TRUE))#Lodde,Barentshavslodde, Lodde - Island/O Gronl./Jan M
str_view(fishnames, regex("sei", ignore_case = TRUE))#Sei, Sei (oppdrett)
str_view(fishnames, regex("sild", ignore_case = TRUE))#Sild, Feitsild, Nordsjosild,Norsk vaargytende sild, Skagerraksild
str_view(fishnames, regex("kongekrabbe", ignore_case = TRUE))#Kongekrabbe, han-, Kongekrabbe, hun-, Kongegrabbe
```

# Creating clean catches data: unifying species names and municipalities names.
```{r }
#I assume that we don't need maricultured cod and saithe (oppdrett torsk, oppdrett sild), and capeling from Iceland and Greenalnd, Skagerraksild, Nordsjosild
catch_clean <- temp_catch %>% 
              select(-c(7,10)) %>% #remove columns "Region" and "Payed_NOK", we don't need them for now 
              filter(Coast_ocean == "8") %>% #%>% #select only coastal areas
              filter(!Species %in% c("Torsk (oppdrett)", "Polartorsk", "Lodde - Island/O Gronl./Jan M", 
                                     "Sei (oppdrett)", "Skagerraksild" )) %>% 
              filter(Species %in% c("Annen Torsk","Annen torsk","Nordostarktisk torsk","Skrei","Hyse","Nordostarktisk hyse", 
                                    "Annen hyse", "Sei", "Lodde","Barentshavslodde","Sild","Feitsild", "Kongekrabbe", "Norsk vaargytende sild")) %>% 
              mutate(Species = replace(Species, Species %in% c("Annen Torsk","Annen torsk" , "Nordostarktisk torsk", "Skrei"), "Torsk")) %>% 
              mutate(Species = replace(Species, Species %in% c("Nordostarktisk hyse", "Annen hyse"), "Hyse")) %>% 
              mutate(Species = replace(Species, Species == "Barentshavslodde", "Lodde")) %>% 
              mutate(Species = replace(Species, Species %in% c("Kongekrabbe, hun-", "Kongekrabbe, han-"), "Kongekrabbe")) %>%   
              mutate(Species = replace(Species, Species %in% c("Feitsild", "Norsk vaargytende sild"), "Sild")) %>% 
              left_join(names[,c(4,6)], by = c("Species" = "Common..Norw.")) %>% 
              rename("English" = "Common..Eng.") %>% 
              left_join(komlist[,c(1,2)], c("Municip_number" = "Komnum")) %>% 
              select(-4) %>% 
              rename("Municip_name" = "Name") %>% 
              select(c(1,2,3,9,8,7,6))
  
kable(head(catch_clean, 5)) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F)
```

# Final cleaning: inserting missing names of municipalities, aggregating catch data for months and fleet sizes
```{r}
catch_final <- catch_clean %>% 
             mutate(Municip_name = as.character(Municip_name)) %>% 
             mutate(Municip_name = replace(Municip_name, Municip_number == 1839, "Beiarn")) %>% 
             mutate(Municip_name = replace(Municip_name, Municip_number == 1842, "Skjerstad_2005")) %>% 
             mutate(Municip_name = replace(Municip_name, Municip_number == 1901, "Harstad_2013")) %>% 
             mutate(Municip_name = replace(Municip_name, Municip_number == 1915, "Bjarkoy_2013")) %>% 
             mutate(Municip_name = replace(Municip_name, Municip_number == 2011, "Guovdageaidnu-Kautokeino")) %>% 
             group_by(Year,Municip_number,Municip_name,English) %>% 
             summarize(Total_catch = sum(Catch_weight))

write_csv(catch_final,"data/fish_catch_by_municipality.csv")
```
