---
title: "Catch per species in 6 municipalities (Tromso, Vardo, Hammerfest, Skervoy, Vega, Svolvaer)"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output:
  html_document:
    css: '~/github/nor-prep/prep/templates/style.css'
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/nor-prep/prep/templates/norway_banner.html'
  pdf_document:
    toc: true
---
```{r message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message = FALSE, warning= FALSE, message = FALSE)
source('~/github/nor-prep/prep/src/common.R')
```

```{r libraries, results="hide"}
library(ggthemes)
library(janitor)
```

# Load catch data
```{r}
catch <- read.csv("data/fish_catch_by_municipality.csv")
```

# Filtering out the six municipalities (Vardo, Hammerfest,Skervoy,Tromso, Vega, Vagan)
```{r}
visitedmp <-catch %>% 
  filter(Municip_name %in% c("Vardo", "Hammerfest", "Skjervoy", "Tromso", "Vega", "Vagan")) %>% 
  droplevels()
```

http://yutannihilation.github.io/allYourFigureAreBelongToUs/ggthemes/theme_stata/

## Creating ggplot theme and additional functionalities for plots
```{r}
#breaks1 <- seq(1994, 2018, by = 2) 
#labels1 <- as.character(breaks1) 

find_breaks <-function(x){
  rng <- range(x, na.rm = TRUE)
  seq(plyr::round_any(rng[1], 100, floor), plyr::round_any(rng[2], 100), length.out = 4)
}


# Use map() to iterate over find_breaks() : nice_breaks
nice_breaks <-map(catch_mpp, ~ find_breaks(.$Total_catch))

theme_map <- function(...) {
   theme_stata(scheme = "s2color") + 
    theme(
      legend.position = "none",
      axis.text.x = element_text(
        size = 8, angle = 90, hjust = 1, vjust = 0.5,
        face = "bold"
      ),
      axis.text.y = element_text(size = 10, angle = 0, face = "bold"),
      axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0), face = "bold", size = 12, color = "darkblue"),
      plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold"),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2, "cm"),
      strip.text = element_text(size = 12, face = "bold")
    )
}
```

# Plots per municipality and specues (just for examination)
##  Plot1: all species at once in a line plot
```{r}
catch_mpp <- split(visitedmp, visitedmp$Municip_name)

catch_mpp[[2]] <- filter(catch_mpp[[2]], !English == "Atlantic herring")#filter out the single landing of Atlantic herring in Skervoy, it will not be visible on plots anyway

plots1 <- map2(
  catch_mpp,
  names(catch_mpp),
  ~ ggplot(data = .x, mapping = aes(x = Year, y = Total_catch)) +
    geom_line(color = "darkseagreen", size = 2) +
    ggtitle(.y) +
    facet_wrap(English ~ .) +
    scale_x_continuous(breaks = breaks1, labels = labels1) +
    labs(y = "Fangst, tonn", x = "") +
    theme_map())


               
```

## Just another version
```{r}

plots2 <- pmap(
   list(catch_mpp, names(catch_mpp), nice_breaks),
  ~ ggplot( data = ..1, mapping = aes(x = Year, y = Total_catch)) +
    geom_line(color = "darkseagreen", size = 2) +
    ggtitle(..2) +
    facet_wrap(English ~ .) +
    scale_x_continuous(breaks = breaks1, labels = labels1) +
    scale_y_continuous(breaks = ..3) +
    labs(y = "Fangst, tonn", x = "") +
    theme_map())

file_names <- paste0("figs/municipality_catch", "_", names(catch_mpp), ".pdf")
 map2(file_names, plots2, ggsave)
```

# All species amd municipalities together
```{r}
library(wesanderson)
breaks2 <- seq(0, 320000, by = 50000)

plot3 <- ggplot( data = visitedmp, mapping = aes(x = Year, y = Total_catch)) +
    geom_line(aes(color = English),size = 1.5) +
    scale_color_brewer(type = qual, palette = "RdYlGn", direction = -1, name = "Species") +
    facet_wrap(Municip_name ~ .) +
    scale_x_continuous(breaks = breaks1, labels = labels1) +
    scale_y_continuous(breaks = breaks2) +
    labs(y = "Catch, tonn", x = "") +
       theme_stata(scheme = "s2color") + 
    theme(
      axis.text.x = element_text(
        size = 8, angle = 90, hjust = 1, vjust = 0.5,
        face = "bold"),
      axis.text.y = element_text(size = 10, angle = 0, face = "bold"),
      axis.title.y = element_text(margin = margin(t = 0, r = 15, b = 0, l = 0), face = "bold", size = 12),
      plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold"),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2, "cm"),
      strip.text = element_text(size = 12, face = "bold") 
    )
 ggsave("figs/catch_in_workshop_municipalities.pdf", plot3)
```

