---
title: "Dowloading ICES data on stocks assessment"
author: "Marina"
date: "1/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, results="hide"}
library(ggthemes)
library(janitor)
library(DT)
library(tidyr)
library(tidyverse)
```

```{r}
library("icesSAG")
library(rebus)
```

```{r}
stocks_raw <- getListStocks(0) 
  
stocks_prep <- stocks_raw %>% 
  dplyr::select(c(AssessmentKey, AssessmentYear, SpeciesName))
```
Following a tutorial at: 
http://ices.dk/marine-data/Documents/StockAssessment/intro-sag.pdf

Selecting all the stocks form the Barents and Norwegian Seas (areas 27.1 and 27.2)
```{r}
bar_nor <- str_detect(
  stocks_raw$StockKeyLabel,
  ANY_CHAR %R%
    or("27.1", "27.2") %R%
    negated_char_class(DGT)
) 


nea <- str_detect(
  stocks_raw$StockKeyLabel,
  ANY_CHAR %R%
    "27.nea" %R%
    END
)

coast_arct <- 
  str_detect(
  stocks_raw$StockKeyLabel,
  ANY_CHAR %R%
    or("coas", "arct") %R%
    END)

stocks_nea <- bind_rows(list(
  stocks_raw[bar_nor, ],
  stocks_raw[nea, ],
  stocks_raw[coast_arct,]
))
```


```{r}
#cod, capelin, herring, saithe, halibut, makerel, b.whiting, redfish, haddock.
species_keys <- stocks_nea %>% 
  filter(SpeciesName %in% c(
    "Reinhardtius hippoglossoides",
    "Clupea harengus",
     "Pollachius virens",
     "Scomber scombrus",
     "Gadus morhua",
     "Micromesistius poutassou",
     "Sebastes norvegicus",
     "Mallotus villosus",
    "Melanogrammus aeglefinus"
    ))  %>%
    pull(AssessmentKey)

```

# Get the stock summary tables for all species
```{r}
# just to try getting stock summaries for one species (capelin) 
#stock_status <- getSummaryTable(9192)[[1]]

stock_status <- map(species_keys, ~ getSummaryTable(.x)[[1]]) %>%
  do.call("rbind", .) %>%
  group_by(fishstock) %>%
  filter(AssessmentYear == max(unique(AssessmentYear)))
```

```{r}
stock_msy <- getFishStockReferencePoints(species_keys) %>% 
  do.call("rbind", .) %>% 
  group_by(AssessmentYear,AssessmentKey, StockKeyLabel,FLim, Blim, FMSY, MSYBtrigger) %>% 
  tally()

#write.csv(stock_msy, "data/ices_stock_msy.csv", row.names = F)
```

Megre the stocks status table with MSY table, using the StockKeyLabel as a key
```{r}
stocks_labels <- stocks_nea %>% 
  group_by(StockKeyLabel,SpeciesName, StockDescription) %>% 
  summarize(n = n()) 

stocks_final_df <- stock_status %>% 
  left_join(stocks_labels[,c(1,2,3)], by = c("fishstock" = "StockKeyLabel")) %>% 
  as.tibble(.) %>% 
  dplyr::select(-c(
            AssessmentYear,
            recruitment, 
            high_recruitment, 
            low_recruitment,
            catches,
            landings,
            discards,
            StockPublishNote,
            Purpose,
            recruitment_age,
            units,
            stockSizeDescription,
            stockSizeUnits,
            fishingPressureDescription,
            fishingPressureUnits)) %>%  
  filter(StockDescription != "")


#write.csv(stocks_final_df, "data/ices_stocks_ssb.csv", row.names = F)
```


Which stocks did not have FMSY information for all years:
```{r}
filter(stock_msy, is.na(FMSY)) %>% 
  count(StockKeyLabel)
```




