---
title: "Some plots exploring the fisheries data"
author: "Document Author"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('~/github/nor-prep/prep/src/common.R')
```

```{r include = FALSE}
library(readxl)
library(ggthemes)
library(scales)
library(zoo)
library(readr)
```


# Load the data tables
```{r}
stocks_stat <- read_csv("data/stock_scores.csv")
catch <-read_csv("data/area_weighted_catch_and_catchscore.csv")
```

## Overview of fisheries data and scores with ggplots:
Compare total proportions of catch per stock  
```{r, warning=FALSE}
breaks1 <- seq(1994, 2018, by = 1)
labels1 <- as.character(breaks1)
labels1[!breaks1%%2==0]<- ""

plot_catches <- catch %>% 
                group_by(Year, Species) %>% 
                summarize(catch_spp = sum(Total_catch_new)) %>% 
                group_by(Year) %>% 
                mutate(catch_grandtot = sum(catch_spp)) %>% 
                ungroup() %>% 
                mutate(catch_prop = (catch_spp/catch_grandtot)*100)
                
ggplot(plot_catches, aes(x = Year, y = catch_prop, fill= Species))+
  geom_bar(stat = "identity")+
  scale_x_continuous(breaks = breaks1, labels = labels1)+
  labs(x = "", y = "Total catch proporiton, %")+
  theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 1, vjust = 0.5, face = "bold", colour = "black"),
        axis.text.y = element_text(size = 10, face = "bold",colour = "black"),
        legend.text = element_text(face = "italic"),
        legend.title = element_blank())+
  theme_hc()+
  scale_fill_viridis_d(option = "D") 
```


## Total catch per species and municipality (figures are uploaded as pdf) 
```{r message=FALSE} 
catch_bycounty <-catch %>% 
             mutate(county = case_when(
                                    Municip_number >= 1800 &  Municip_number < 1900 ~ "Nordland",
                                    Municip_number >= 1900 &  Municip_number < 2000 ~ "Troms",
                                    Municip_number >= 2000 ~ "Finnmark")) %>% 
                                    mutate(log_catch = log(Total_catch_new + 1))


counties <- unique(catch_bycounty$county) 

#To redefine breaks:
# breaks1 <- seq(1994, 2018, by = 1)
# labels1 <- as.character(breaks1)
# labels1[!breaks1%%2==0]<- ""

for(i in 1:length(counties))
  {
  cty <- counties[i]
  
  df <- catch_bycounty %>%
    filter(county == cty)
  
  species <- unique(df$Species)
  
  for(j in 1:length(species)){
  sp <- species[j]
    
  df2 <- df %>% 
    filter(Species == sp)
  
  plot <- ggplot(df2)+
      geom_col(aes(x = Year, y = log_catch), fill = "dodgerblue4")+
      facet_wrap(Municip_name_new  ~ .) +
      scale_x_continuous(breaks = breaks1, labels = labels1)+
      scale_y_continuous(limits = c(0,12), breaks = seq(0, 12, by = 2)) +
      labs(y = "log(Total catch)", x = "") +
      ggtitle(paste(cty, "_", sp))+
      theme_stata(scheme = "s1color") +
      theme(legend.position = "none", 
            axis.text.x = element_text(size = 5, angle = 90, hjust = 0.5, vjust = 0.5, face = "bold"),
            axis.text.y = element_text(size = 6, face = "bold", hjust = 0.5, vjust = 0.5, margin = margin(t = 0, r = 2, b = 0, l = 0)),
            plot.title = element_text(hjust=0.5, vjust=0.5),
            axis.ticks.x = element_line(size = 0.5),
            axis.ticks.length = unit(0.2, "cm"))
           
            
ggsave(paste0("figs/catch_", cty, "_", sp, ".pdf"), plot)
  
}
  
}


```

# Catch of all species per municipality
I use the same loop as in the chunk above but do not nest by species.
```{r}
for(i in 1:length(counties))
  {
  cty <- counties[i]
  
  df <- catch_bycounty %>%
    filter(county == cty) %>% 
    group_by(Year,
             Municip_number,
             Municip_name_new,
             county) %>% 
    summarise(all_catches = sum(Total_catch_new)) %>% 
    mutate(log_all_catches = log(all_catches + 1))
    
    
plot <- ggplot(df)+
      geom_col(aes(x = Year, y = log_all_catches), fill = "dodgerblue4")+
      facet_wrap(Municip_name_new  ~ .) +
      scale_x_continuous(breaks = breaks1, labels = labels1)+
      scale_y_continuous(limits = c(0,12), breaks = seq(0, 12, by = 2)) +
      labs(y = "log(Total catch)", x = "") +
      ggtitle(cty)+
      theme_stata(scheme = "s1color") +
      theme(legend.position = "none", 
            axis.text.x = element_text(size = 5, angle = 90, hjust = 0.5, vjust = 0.5, face = "bold"),
            axis.text.y = element_text(size = 6, face = "bold", hjust = 0.5, vjust = 0.5, margin = margin(t = 0, r = 2, b = 0, l = 0)),
            plot.title = element_text(hjust=0.5, vjust=0.5),
            axis.ticks.x = element_line(size = 0.5),
            axis.ticks.length = unit(0.2, "cm"))
           
            
ggsave(paste0("figs/catch_all_species", cty, ".pdf"), plot)
  
}
  


```




# How SSB per species varied accross years in relation to Blim and Bmsy?
```{r message=FALSE}

plot_stocks_prep <- stocks_stat %>% 
  select(-X) %>% 
  filter(!English %in% c(
    "Greenland halibut",
     "Redfish",
     "Blue whiting"
  ))



 plot_stocks_prep2 <- plot_stocks_prep %>% 
       select(Year, English, SSB, MSYBtrigger, Blim) %>% 
       mutate(SSB = as.numeric(as.character(SSB))) %>% 
       mutate(Year = as.numeric(as.character(Year)))

 stocks_spp <-unique(plot_stocks_prep2$English)
 
 for (i in 1:length(stocks_spp)) {
   
 sp <-stocks_spp[i]  
 df <- plot_stocks_prep2 %>% 
       filter(English == sp)
 bmsy = df$MSYBtrigger[1]
 blim = df$Blim[1]
 
options(scipen = 999) 

plot2 <- ggplot(df)+
      geom_col(aes(x = Year, y = SSB), fill = "dodgerblue")+
      scale_x_continuous(breaks = breaks1, labels = labels1)+
      scale_y_continuous(limits = c(0, max(df$SSB, na.rm = T)))+
      labs(y = "SSB", x = "") +
      geom_hline(aes(yintercept = Blim), col = "darkred", linetype = "dashed", size = 1) +
      geom_hline(aes(yintercept = MSYBtrigger), col = "darkgreen", linetype = "dashed", size = 1) +
      ggtitle(sp) +
      annotate("text", x = 1994, y = (bmsy + 20000), label = "MSYBtrigger", hjust = 0, color = "darkgreen", size = 7)+
      annotate("text", x = 1994, y = (blim + 20000), label = "Blim", hjust = 0, color = "darkred", size = 7)+
      theme_stata(scheme = "s1color") +
      theme(legend.position = "none", 
             axis.title = element_text(size = 15),
             axis.text.x = element_text(size = 12, angle = 45, hjust = 1, vjust = 0.5, face = "bold"),
             axis.text.y = element_text(size = 12, face = "bold", margin = margin(t = 0, r = 0, b = 0, l = 0),
                                        angle = 0, hjust = 1, vjust = 0),
             plot.title = element_text(hjust=0.5, vjust=0.5),
             axis.ticks.x = element_line(size = 0.5),
             axis.ticks.length = unit(0.2, "cm"),
             strip.text = element_text(size = 15))  

ggsave(paste0("figs/SSB_", "_", sp, ".pdf"), plot2)      
        
 } 

```






