---
title: "Cleaning the data on age of fishermen in each municipality"
author: "Marina Espinasse"
date: "`r Sys.Date()`"
output:
  html_document:
    css: '~/github/nor-prep/prep/templates/style.css'
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/nor-prep/prep/templates/norway_banner.html'
  pdf_document:
    toc: true

---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('~/github/nor-prep/prep/src/common.R')
```

```{r}
age_finnmark <- read_excel(file.path("~/github/nor-prep/prep/small_sc_fisheries/data/Alder-hovedyrke-kommune-1983-2019.xlsx"), 
                  sheet = 1, skip = 5)

age_finnmark_prep <- age_finnmark %>% 
  rename(municip_name = X__1, 
         year = X__2,
         age = X__3,
        "2019" = "20191)") %>% 
  mutate(municip_name = zoo::na.locf(municip_name)) %>% 
   mutate(year = zoo::na.locf(year)) %>% 
  filter(!str_detect(.$municip_name,
                    pattern = "^Totalt." ))
```

