---
title: "Plotting trends in the PRR sustainability index"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    css: '~/github/nor-prep/prep/templates/style.css'
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/nor-prep/prep/templates/norway_banner.html'
  pdf_document:
    toc: true
---

```{r message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message = FALSE, warning= FALSE, message = FALSE)
source('~/github/nor-prep/prep/src/common.R')
```

```{r libraries, results="hide"}
library(ggthemes)
library(here)
```

# Import data
```{r}
prr <- read.csv(here("prep", "food_provision", "mariculture", "data", "prr_score_per_mcp.csv"))
komnames_norw <- read_excel(file.path("~/github/aqua_fish_paper/data/raw/komlist_norw.xlsx"))
```


# Prepare the data for plotting
We need to add a county column to the table of PRR index
```{r}
prr_plot <- prr %>% 
  mutate(county = case_when(
    municip_number >= 1800 & municip_number < 1900 ~ "Nordland",
    municip_number >= 1900 & municip_number < 2000 ~ "Troms",
    municip_number >= 2000 ~ "Finnmark"
  ))
```

Add names of municipalities with their special Norwegian letters
```{r}
prr_plot2 <- prr_plot %>% 
  left_join(komnames_norw[c("Komnum", "Norw_name")], by = c("municip_number" = "Komnum"))
```


# Plotting
## Theme for prr colourfull plots
```{r}
theme_prr_publ <- function(...) {
  theme_stata(scheme = "s1color") +
    theme(
      legend.position = "none",
      axis.text.x = element_text(
        size = 6, angle = 90, hjust = 1, vjust = 0.5,
        face = "bold"
      ),
      axis.text.y = element_text(size = 7, angle = 0),
      axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
      plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "bold"),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2, "cm"),
      strip.text = element_text(size = 10, face = "bold"),
      strip.background = element_rect(fill = "bisque", color ="bisque"),
      panel.background = element_rect(fill = "white"),
     #panel.border = element_rect(color = "grey97"),
      plot.background = element_blank(),
      panel.grid.major.x = element_line(color = "grey97", size = 0.5),
    )
}
```


```{r}
breaks1 <- seq(2004, 2018, by = 1)
labels1 <- as.character(breaks1)
labels1[!breaks1%%2==0]<- ""

county_names <- list("Finnmark", "Nordland", "Troms")

prr_df <- split(prr_plot2, prr_plot2$county)

plots_prr <- map2(
  prr_df, 
  names(prr_df),
   ~ ggplot(data = .x, mapping = aes(x = year, y = prr_score)) +
  geom_point(color = "darkgreen", size = 0.5) +
  geom_smooth(color = "darkslategray",
              size = 0.4,
               fullrange = FALSE,
               method = "loess",
               span = 0.75) +
  ggtitle(.y)  +
  facet_wrap(Norw_name ~ .) +
  scale_x_continuous(breaks = breaks1, labels = labels1) +
  scale_y_continuous(limits = c(0, 1.2), breaks = c(0, 0.2, 0.4, 0.6, 0.8,1)) +
  labs(y = "PRR index", x = "") +
  theme_prr_publ())

 file_names <- paste0("figs/prr_score_trends_publ", "_", county_names, ".pdf")
 map2(file_names, plots_prr, ggsave)
```