---
title: "Protein efficiency ratio"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    css: '~/github/nor-prep/prep/templates/style.css'
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/nor-prep/prep/templates/norway_banner.html'
  pdf_document:
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
source("~/github/nor-prep/prep/src/common.R")
```

```{r libraries, results="hide"}
library(ggthemes)
library(janitor)
```

# Loading aquaculture production data and calculating protein efficiency based on average constant for trout and salmon
```{r}
akva_raw<-read_excel(file.path(dir_M[2],"Aquaculture/Akvadataut.xlsx")) 
```

# Cleaning aquaculture production table
```{r}
protein_prep <- akva_raw[-c(1:3), ]
colnames(protein_prep) <- akva_raw[3, ]

# Deleting duplicated columns 
protein_prep2 <- protein_prep[!duplicated(names(protein_prep), fromLast = TRUE)]

estimate_per <- function(arg1, arg2) {
  if (any(is.na(c(arg1, arg2)))) {
    return(NA)
  } else if (arg1 == 0 | arg2 == 0) {
    return(NA)
  } else {
    nom <- arg1 * 0.60 * 0.191
    denom <- arg2 * 0.938 * 0.354
    per <- nom / denom
  }
  per
}


protein_prep3 <- protein_prep2 %>%
  clean_names(.) %>%
  mutate(total_prod_corrected = ifelse(
    total_production < 0, 0, total_production
  )) %>%
  mutate(feed_used_kg = as.numeric(feed_used_kg)) %>%
  mutate(total_prod_corrected = as.numeric(total_prod_corrected)) %>%
  rowwise() %>%
  mutate(protein_new = estimate_per(
    total_prod_corrected, feed_used_kg
  ))

```

# Final table preparation
```{r}
protein_final <- protein_prep3 %>%
  select(c(1:7,35)) %>%
  filter_at(vars(8), all_vars(!is.na(.)))
#write_csv(protein_final, "data/protein_efficiency_ratio.csv")
```



