---
title: "Protein retention rate"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    css: '~/github/nor-prep/prep/templates/style.css'
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/nor-prep/prep/templates/norway_banner.html'
  pdf_document:
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
source("~/github/nor-prep/prep/src/common.R")
```

```{r libraries, results="hide"}
library(ggthemes)
library(janitor)
```

# Loading aquaculture production data
```{r}
akva_raw<-read_excel(file.path(dir_M[2],"Aquaculture/Akvadataut.xlsx")) 
```

# Cleaning aquaculture production table
```{r}
protein_prep <- akva_raw[-c(1:3), ]
colnames(protein_prep) <- akva_raw[3, ]

# Deleting duplicated columns 
protein_prep2 <- protein_prep[!duplicated(names(protein_prep), fromLast = TRUE)]

protein_final <- protein_prep2 %>%
  select(c(1:7,26)) %>%
  filter_at(vars(8), all_vars(!is.na(.))) %>% 
  clean_names(.)   

write_csv(protein_final, "data/protein_retention_ratio.csv")
```




