---
title: "Protein retention ratio"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    css: '~/github/nor-prep/prep/templates/style.css'
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/nor-prep/prep/templates/norway_banner.html'
  pdf_document:
    toc: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
source("~/github/nor-prep/prep/src/common.R")
```

```{r libraries, results="hide"}
library(ggthemes)
library(janitor)
```

# Loading aquaculture production data 
```{r}
akva_raw<-read_excel(file.path(dir_M[2],"Aquaculture/Akvadataut.xlsx")) 
```

# Cleaning aquaculture production table
```{r}
protein_prep <- akva_raw[-c(1:3), ]
colnames(protein_prep) <- akva_raw[3, ]

# Deleting duplicated columns 
protein_prep2 <- protein_prep[!duplicated(names(protein_prep), fromLast = TRUE)]
```

# Calculating protein retention
```{r}

estimate_prr <- function(arg1, arg2) {
  if (any(is.na(c(arg1, arg2)))) {
    return(NA)
  } else if (arg1 == 0 | arg2 == 0) {
    return(NA)
  } else {
    nom <- arg1 * 0.60 * 0.186
    denom <- arg2 * 0.934 * 0.356
    per <- nom / denom
  }
  per
}


protein_prep3 <- protein_prep2 %>%
  clean_names(.) %>%
  select(c(1,2,3,4,5,6,7,8,9, 14)) %>% 
  mutate_at(c(5,6,7,8,9,10), as.numeric) %>%     #mutate all the columns that have to be numeric 
  rowwise() %>%
  mutate(total_prod =  sum(trout_prod_kg, salmo_prod_kg, na.rm = T)) %>%
  mutate(protein_eff = estimate_prr(
    total_prod, feed_used_kg
  ))

```


```{r}
#write_csv(protein_prep3, "data/protein_retention_ratio.csv")
```



