---
title: "Protein retention ratio"
author: "Sigrid Engen"
date: "17 april 2019"
output: html_document
---

# Sustainability index
## Protein retention rate - municipality level Northern-Norway

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,warning=FALSE, message=FALSE)
```

```{r libraries, results="hide"}
library(knitr)
library(dplyr)
library(ggplot2)
library(ggthemes)
```

```{r data}
akva<-read.table("raw/Akvadataut.csv", header=TRUE, sep=";") #load data
akva<-na.omit(akva)# remove NAs
prod<-select(akva, Kname, Yrs, Knr2017,Protein.retention.ratio)#subset variables  
head(prod)
#write.csv(prod, "data/protein_retention_ratio_mariculture.csv")# don't write the csv file until we know if it is okay to 
```

## Plot protein retention rate
```{r plot protein retention}

breaks1 <- seq(1994, 2018, by = 4) # decide where to write label on x-labels
labels1 <- as.character(breaks1) 
labels1[!breaks1%%2==0]<- "" 

prod <- prod[-c(487),]#remove outlier - figure out what is wrong with this!

plot <- ggplot(prod)+ 
       geom_col(aes(x = Yrs, y = Protein.retention.ratio), fill = "dodgerblue4")+ 
       facet_wrap(Kname  ~ .) + 
       scale_x_continuous(breaks = breaks1, labels = labels1)+ 
       labs(y = "Protein retention ratio", x = "") + 
       theme_stata(scheme = "s1color") + 
       theme(legend.position = "none",  
           axis.text.x = element_text(size = 6, angle = 90, hjust = 1, vjust = 0.5, face = "bold"), 
             axis.text.y = element_text(size = 7, angle = 0), 
             #scale_y_discrete(breaks, c(""))
             plot.title = element_text(hjust=0.5, vjust=0.5), 
             axis.ticks.x = element_line(size = 0.5), 
             axis.ticks.length = unit(0.2, "cm"), 
             strip.text=element_text(size=13)) 
             
              
#ggsave(paste0("figs/protein_retention", ".png"), plot) 
    

```

```{r echo=FALSE, fig.width=15, fig.height=10}
plot
```
