---
title: "Salmon lice prevalence - mariculture"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: "C:/github/nor-prep/prep/templates/norway_banner.html"
  pdf_document:
    toc: true
---
### Load libraries
```{r, message =FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
library(varhandle)
library(tidyr)
library(ggplot2)
```
### Load data
```{r,  results="hide"}
#load data on lice counts 
lus<-read.table("raw/lakselus_per_fisk.csv", header=TRUE, sep=";")
colnames(lus)[colnames(lus) == 'År'] <- 'Ar'#Change from År to Ar - R doesn't like Å

#load data on study municipalities to subset the lice data to incude only these municipalities
munic<-read.table("C:/github/nor-prep/prep/administrative/komlist.csv", header=TRUE, sep=";")
colnames(munic)<- c("Kommunenummer", "Kommune", ("Kid"))
```

### Data cleaning
```{r,  results="hide"}

#Subsetting - extract info on lice for study municipalities
lus_to<-semi_join(lus, munic, by="Kommunenummer") 

#Look here for info on the warning that pops up https://stackoverflow.com/questions/30468412/dplyr-join-warning-joining-factors-with-different-levels

#Remove fish farming localities where there is no activity (Norw;Brakklagt)
lus_to<-subset(lus_to, Brakklagt == "Nei") 

#Remove localities where they have not counted lice
lus_to<-subset(lus_to, Har.telt.lakselus == "Ja") 

#Remove rows from 2019, because this year is not comparable to the others since we only halfway through
lus_to<-subset(lus_to, !Ar == 2019) 

#Remove redundant variables
lus_to<-data.frame(lus_to$Lokalitetsnavn,lus_to$Kommune, lus_to$Over.lusegrense.uke, lus_to$Ar)

#change colnames to English
colnames(lus_to)<- c("Locality", "Municipality", "Above_lice_limit", "Year")

#revalue variable "above lice limit" from yes/no to 1/0 for summarizing later
lus_to$Above_lice_limit<-revalue(lus_to$Above_lice_limit, c("Ja"="1", "Nei" ="0")) 

#change from factor to numeric
lus_to$Above_lice_limit<-unfactor(lus_to$Above_lice_limit)
```
###Calculating proportions
#### the proportion of active localities in the municipality that had more salmon lice than allowed one or more times within a given year
```{r,  results="hide"}
#sumarize the number of times the locality had a lice count above the limit within a year
lus_group<-group_by(lus_to, Locality, Year, Municipality)
sum_local<-as.data.frame(summarise(lus_group, sum_lus = sum(Above_lice_limit, na.rm=TRUE)))

#code all localities that had a lice number above the limit in a year as 1 and rest 0 
sum_local$sum_lus[ sum_local$sum_lus>0 ] <- 1

#sum number of localities that had above lice limit within a year by municipality
muni_group<-group_by(sum_local, Municipality, Year)
sum_munic_abovelim<-as.data.frame(summarise(muni_group, above_lim_number = sum(sum_lus, na.rm=TRUE)))

#need also to know the number of localities where they counted lice but number was below limit - find the total number of localities where they counted lice each year
#https://stackoverflow.com/questions/26720349/get-dplyr-count-of-distinct-in-a-readable-way

sum_muni_loc<-as.data.frame(
  lus_to %>%                    # take the data.frame "data"
  filter(!is.na(Locality)) %>%    # Using "data", filter out all rows with NAs in Locality 
  group_by(Municipality, Year) %>% # Then, with the filtered data, group it by "Muncipality and Year"
  summarise(Unique_Elements = n_distinct(Locality)))   # Now summarise with unique elements per group

#merge datasets of number of unique locations and number above lice limit
above_lim<-sum_munic_abovelim$above_lim_number
sum_muni_loc$above_lim_number<-above_lim

#calculate proportion above limit out of total locations counted
sum_muni_loc$proportion_above<-sum_muni_loc$above_lim_number/sum_muni_loc$Unique_Elements

#change colnames
colnames(sum_muni_loc)<-c("Municipality","Year","NumberOfLocalities",
                          "Above_limit","ProportionLocalitiesAboveLimit")
```
###Plotting
```{r, message=FALSE}
#make variable for localities below lice limit
sum_muni_loc$Below_limit<-sum_muni_loc$NumberOfLocalities-sum_muni_loc$Above_limit

#change the layout of the dataset - make column for Type of count (number of localities below or above limit)
sum_muni_loc2<-gather(sum_muni_loc, key="Type", value="NumberLocalities", Above_limit, Below_limit)
sum_muni_loc2$Type<-as.factor(sum_muni_loc2$Type)
sum_muni_loc2 <- sum_muni_loc2[,-3]

breaks1 <- seq(2012, 2018, by = 2) # decide where to write label on x-labels
labels1 <- as.character(breaks1) 
labels1[!breaks1%%2==0]<- "" 

plot<-ggplot(data = sum_muni_loc2, aes(x = Year, y = NumberLocalities, fill = Type)) +
      geom_col()+
      facet_wrap(Municipality  ~ .) +
      scale_x_continuous(breaks = breaks1, labels = labels1)+ 
      labs(y = "Localities above lice limit", x = "")+
      theme(legend.position = "bottom",
            legend.title=element_blank(),
             axis.text.x = element_text(size = 6, angle = 90, hjust = 1, vjust = 0.5, face = "bold"), 
             axis.text.y = element_text(size = 5.5, angle = 0), 
             plot.title = element_text(hjust=0.5, vjust=0.5), 
             axis.ticks.x = element_line(size = 0.5), 
             axis.ticks.length = unit(0.2, "cm"), 
             strip.text=element_text(size=6))
      
ggsave(paste0("figs/salmon_lice_localities_above_limit_",".png"), plot) 




```

```{r, echo=FALSE, fig.width=15, fig.height=10}
#run plot again and change some text sizes for optimal visualization in markdown
plot<-ggplot(data = sum_muni_loc2, aes(x = Year, y = NumberLocalities, fill = Type)) +
      geom_col()+
      facet_wrap(Municipality  ~ .) +
      scale_x_continuous(breaks = breaks1, labels = labels1)+ 
      labs(y = "Localities above lice limit", x = "")+
      theme(legend.position = "bottom",
            legend.title=element_blank(),
             axis.text.x = element_text(size = 9, angle = 90, hjust = 1, vjust = 0.5, face = "bold"), 
             axis.text.y = element_text(size = 9, angle = 0), 
             plot.title = element_text(hjust=0.5, vjust=0.5), 
             axis.title.y = element_text(size = 15),
             axis.ticks.x = element_line(size = 0.5), 
             axis.ticks.length = unit(0.2, "cm"), 
             strip.text=element_text(size=10))
plot
```
