---
title: "Sustainable food production (tons) by municipality"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: "C:/github/nor-prep/prep/templates/norway_banner.html"
  pdf_document:
    toc: true
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE,warning=FALSE, message=FALSE)
```
### Load libraries
```{r libraries, results="hide"}
library(knitr)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(tidyr)
```
### Make dataset
```{r data}
#load data on protein retention per municipality
protein<-read.table("data/protein_retention_ratio_mariculture.csv", header=TRUE, sep=",") 

#load data on total production per municipality
production<-read.table("data/total_mariculture_production.csv", header=TRUE, sep=",")

#Make variable showing the amount of sustainable finfish farming in tons, where sustainability is defined as the proportion of edible protein in terms of farmed fish compared with the amount put in in terms of feed
sustprod<-protein$Protein.retention.ratio*production$Total.Production/1000

#combine total production and sustainable production in one dataframe
sustprod<-data.frame(protein,sustprod)

#remove redundant colums
sustprod<-sustprod[, -c(1, 5)]

#Show dataset
head(sustprod)

#write.csv(prod, "data/sustainable_production_mariculture.csv")# don't write the csv file until we know if it is okay to 
```

### Plotting
#### - total sustainable production 
```{r, message =FALSE}

#remove outlier - figure out what is wrong with this (Salangen municipality in 2011)!
sustprod2 <- sustprod[-c(487),]

breaks1 <- seq(1994, 2018, by = 4) # decide where to write label on x-labels
labels1 <- as.character(breaks1) 
labels1[!breaks1%%2==0]<- "" 

plot <- ggplot(sustprod2)+ 
       geom_col(aes(x = Yrs, y = sustprod), fill = "dodgerblue4")+ 
       facet_wrap(Kname  ~ .) + 
       scale_x_continuous(breaks = breaks1, labels = labels1)+ 
       labs(y = "Sustainable mariculture prod (tons)", x = "") + 
       theme_stata(scheme = "s1color") + 
       theme(legend.position = "none",  
             axis.text.x = element_text(size = 6, angle = 90, hjust = 1, vjust = 0.5, 
             face = "bold"), 
             axis.text.y = element_text(size = 7, angle = 0), 
             #scale_y_discrete(breaks, c(""))
             plot.title = element_text(hjust=0.5, vjust=0.5), 
             axis.ticks.x = element_line(size = 0.5), 
             axis.ticks.length = unit(0.2, "cm"), 
             strip.text=element_text(size=8)) 
             
ggsave(paste0("figs/sustainable_production", ".png"), plot) 

```

```{r echo=FALSE, fig.width=15, fig.height=10}
plot
```

### Plotting con't 
#### -proportion sustainable food production out of total production
```{r, message =FALSE}
#make variable for "unsustainable production"
sustprod$unsustprod<-(production$Total.Production/1000)-sustprod$sustprod
sustprod3<-gather(sustprod, key="Type", value="Tons", sustprod, unsustprod)
sustprod3$Type<-as.factor(sustprod3$Type)

#find rownumbers Salangen 2011 - remove this value
newdata <- sustprod3[ which(sustprod3$Yrs=='2011' 
& sustprod3$Knr2017 == "1923"), ]
sustprod3 <- sustprod3[-c(487, 1297),]#remove outlier - figure out what is wrong with this!

breaks1 <- seq(1994, 2018, by = 4) # decide where to write label on x-labels
labels1 <- as.character(breaks1) 
labels1[!breaks1%%2==0]<- "" 

plot<-ggplot(sustprod3, aes(Yrs, Tons))+
      facet_wrap(Kname  ~ .) +
      geom_area(aes(fill=Type))+
      scale_x_continuous(breaks = breaks1, labels = labels1)+ 
      labs(y = "Proportion sustainable mariculture prod (tons)", x = "")+
      theme(legend.position = "none",  
             axis.text.x = element_text(size = 6, angle = 90, hjust = 1, vjust = 0.5, 
             face = "bold"), 
             axis.text.y = element_text(size = 5.5, angle = 0), 
             #scale_y_discrete(breaks, c(""))
             plot.title = element_text(hjust=0.5, vjust=0.5), 
             axis.ticks.x = element_line(size = 0.5), 
             axis.ticks.length = unit(0.2, "cm"), 
             strip.text=element_text(size=8))
      
ggsave(paste0("figs/sustainable_production_proportion",".png"), plot) 

#write.csv(sustprod3, "data/delete.csv")# don't write the csv file until we know if it is okay to 
```

```{r echo=FALSE, fig.width=15, fig.height=10}
plot
```
```


