---
title: "Total aquaculture production"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    css: '~/github/nor-prep/prep/templates/style.css'
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/nor-prep/prep/templates/norway_banner.html'
  pdf_document:
    toc: true
---
```{r message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message = FALSE, warning= FALSE, message = FALSE)
source('~/github/nor-prep/prep/src/common.R')
```

```{r libraries, results="hide"}
library(ggthemes)
library(janitor)
```

# Loading aquaculture production data
```{r}
akva_raw<-read_excel(file.path(dir_M[2],"Aquaculture/Akvadataut.xlsx")) 
```

# Cleaning aquaculture production data
```{r data}
akva_prep <- akva_raw[-c(1:3), ]
colnames(akva_prep) <- akva_raw[3, ]

# Some columns got similar names (those are eutropfication data, which we don't need now)
names_freq <- as.data.frame(table(names(akva_prep)))
duplicated(names(akva_prep)) # columns 27,31,26,37,38,39 are duplicated (all about phoshorus and nitrogen)

#  I delete duplicated columns because they don't allow to clean data fully
akva_prep2 <- akva_prep[!duplicated(names(akva_prep), fromLast = TRUE)]

akva_final <- akva_prep2 %>%
  clean_names(.) %>%
  select(-c(14, 16:33)) %>%
  filter_at(vars(c(8:14)), all_vars(!is.na(.))) %>%
  mutate(total_prod_corrected = ifelse(total_production < 0, 0, total_production))
  
#write_csv(akva_final, "data/total_mariculture_production.csv")
```

# Check the overall distribution of aquaculture production
```{r}

mosaic::fav_stats(akva_final$total_prod_corrected)
# min Q1  median      Q3      max    mean      sd   n missing
#    0  0 3041960 6843759 24784477 4427182 4763020 810       0

densplot_data <- akva_final %>%
  mutate(total_prod_corrected = as.numeric(total_prod_corrected))

dens_plot <- ggplot(data = densplot_data) +
  geom_density(
    mapping = aes(x = total_prod_corrected),
    fill = "salmon", color = "darkred", alpha = 0.7
  ) +
  scale_x_continuous(labels = scales::comma) +
  labs(x = "Total aquaculture production, kg") +
  theme(axis.text = element_text(size = 12)) +
  theme_gdocs()

dens_plot
```



# Estiamte difference in the total production year to year - yearly produciton growth rate
```{r}
prod_growth <- akva_final %>%
  group_by(knr2017, kname) %>%
  mutate(previous_prod = lag(total_prod_corrected)) %>%
  filter(!is.na(previous_prod)) %>%
  mutate(total_prod_corrected = as.numeric(total_prod_corrected)) %>% 
  mutate(previous_prod = as.numeric(previous_prod)) %>% 
  mutate(growth = (total_prod_corrected - previous_prod) /previous_prod) 

average_growth <- prod_growth %>%
  filter(!is.infinite(growth) & growth >= 0) %>%
  group_by(knr2017, kname) %>%
  summarize(average_growth = mean(growth),
    mingrowth = min(growth),
    maxgrowth = max(growth)
  )

```


# Plot log(total aquaculture production)
```{r plot total production, message =FALSE}
breaks1 <- seq(2004, 2014, by = 2) # decide where to write label on x-labels
labels1 <- as.character(breaks1) 
#labels1[!breaks1%%2==0]<- "" 

counties <- unique(akva_final$county)

for (i in 1:length(counties)) {
  ct1 <- akva_final[akva_final$county == counties[i], ]

  plot <- ggplot(ct1) +
    geom_col(aes(x = as.numeric(yrs), y = as.numeric(total_prod_corrected)), fill = "dodgerblue4") +
    facet_wrap(kname ~ .) +
    scale_x_continuous(breaks = breaks1, labels = labels1) +
    scale_y_continuous(trans = "log10") +
    labs(y = "Log(Total Mariculture prod (tons))", x = "") +
    ggtitle(counties[i]) +
    theme_stata(scheme = "s1color") +
    theme(
      legend.position = "none",
      axis.text.x = element_text(
        size = 6, angle = 90, hjust = 1, vjust = 0.5,
        face = "bold"
      ),
      axis.text.y = element_text(size = 7, angle = 0),
      axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
      plot.title = element_text(hjust = 0.5, vjust = 0.5),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2, "cm"),
      strip.text = element_text(size = 12)
    )

  ggsave(paste0("figs/tot_prod", "_", counties[i], ".pdf"), plot)
}

```

## Creating ggplot theme
```{r}
theme_map <- function(...) {
  theme_stata(scheme = "s1color") +
    theme(
      legend.position = "none",
      axis.text.x = element_text(
        size = 6, angle = 90, hjust = 1, vjust = 0.5,
        face = "bold"
      ),
      axis.text.y = element_text(size = 7, angle = 0),
      axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0)),
      plot.title = element_text(hjust = 0.5, vjust = 0.5),
      axis.ticks.x = element_line(size = 0.5),
      axis.ticks.length = unit(0.2, "cm"),
      strip.text = element_text(size = 12)
    )
}
```


## Plotting total acquaculture production using purrr
```{r}
county_names <- list("Finnmark", "Nordland", "Troms")

counties_df <- split(akva_final, akva_final$county)

plots_akva <- map2(
  counties_df, 
  names(counties_df),
   ~ ggplot(data = .x, mapping = aes(x = as.numeric(yrs), y = as.numeric(total_prod_corrected))) +
  geom_col(fill = "dodgerblue4") +
  ggtitle(.y)  +
  facet_wrap(kname ~ .) +
  scale_x_continuous(breaks = breaks1, labels = labels1) +
  scale_y_continuous(trans = "log10") +
  labs(y = "Log(Total Mariculture prod (tons))", x = "") +
  theme_map())

 file_names <- paste0("figs/tot_prod", "_", county_names, ".pdf")
 map2(file_names, plots_akva, ggsave)

```

 
 
 
